-- ============================================================
-- seed.sql — sample data to demo the autonomous pivot end-to-end
-- In production, Vibe_Clusters/Tracks/Cluster_Adjacency rows are
-- generated by ml/cluster_tracks.py + ml/adjacency_map.py, then
-- loaded here (or via a generated seed file with the same shape).
-- ============================================================

-- Vibe Clusters (low energy -> high energy, illustrative)
INSERT INTO Vibe_Clusters (cluster_id, vibe_name) VALUES
    (1, 'Chill / Lo-fi'),
    (2, 'Groove / Mid-tempo'),
    (3, 'Peak / High-energy'),
    (4, 'Anthemic / Festival Banger');

-- Adjacency map: which cluster to jump to, and how much more
-- energy it carries (energy_delta), when the current one is failing
INSERT INTO Cluster_Adjacency (cluster_id, adjacent_cluster_id, energy_delta) VALUES
    (1, 2, 1),
    (1, 3, 2),
    (2, 3, 1),
    (2, 4, 2),
    (3, 4, 1);

-- Tracks (a handful per cluster for demo purposes)
INSERT INTO Tracks (track_id, cluster_id, title, artist_name, duration) VALUES
    (101, 1, 'Slow Tide', 'Artist A', 210),
    (102, 1, 'Soft Static', 'Artist B', 198),
    (201, 2, 'Mid Pulse', 'Artist C', 220),
    (202, 2, 'Groove Line', 'Artist D', 205),
    (301, 3, 'Peak Hour', 'Artist E', 195),
    (302, 3, 'Overdrive', 'Artist F', 200),
    (401, 4, 'Anthem Rise', 'Artist G', 215),
    (402, 4, 'Festival Lights', 'Artist H', 208);

-- Stages
INSERT INTO Stages (stage_id, stage_name, curr_vibe_score) VALUES
    (1, 'Main Stage', 0),
    (2, 'Sunset Stage', 0);

-- Seed an initial "now playing" row for Stage 1 so pivot_vibe()
-- has something to pivot away from during a demo
INSERT INTO Live_Queue (stage_id, track_id, play_order, status) VALUES
    (1, 101, 0, 1),  -- now playing (Chill / Lo-fi)
    (1, 102, 1, 0);  -- pending
