import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import euclidean_distances
import os

# Set seed for reproducibility
np.random.seed(42)

def generate_and_cluster():
    print("Generating synthetic track data...")
    # 4 clusters (representing 4 vibes) with 250 tracks each = 1000 tracks
    # Features: Tempo, Energy, Valence
    X, y_true = make_blobs(n_samples=1000, centers=4, n_features=3, random_state=42, cluster_std=1.5)
    
    # Scale features slightly to resemble audio features 
    # Tempo ~ 80-180, Energy ~ 0-1, Valence ~ 0-1
    # We don't strictly need realism for the DB test, but let's shift values to be positive
    X = np.abs(X)
    
    print("Clustering tracks using K-Means...")
    kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(X)
    centroids = kmeans.cluster_centers_
    
    # Define vibe names based on arbitrary sorting of energy (feature 1)
    # We will sort centroids by energy to assign names logically
    energy_indices = np.argsort(centroids[:, 1])
    
    vibe_names = ["Chill / Lo-fi", "Groove / Mid-tempo", "Peak / High-energy", "Anthemic / Festival Banger"]
    cluster_mapping = {original_idx: new_idx + 1 for new_idx, original_idx in enumerate(energy_indices)}
    
    # Calculate adjacency map based on centroid distance
    print("Calculating cluster adjacency...")
    distances = euclidean_distances(centroids)
    
    adjacency_list = []
    for i in range(4):
        mapped_i = cluster_mapping[i]
        for j in range(4):
            if i != j:
                mapped_j = cluster_mapping[j]
                # If target is higher energy (higher index in our sorted list), delta > 0
                energy_delta = mapped_j - mapped_i
                if energy_delta > 0: # Only care about pivoting to higher energy
                    adjacency_list.append((mapped_i, mapped_j, energy_delta, distances[i, j]))
    
    # Sort by mapped_i, then by shortest distance
    adjacency_list.sort(key=lambda x: (x[0], x[3]))
    
    # Pick the closest higher-energy neighbor for each cluster (if one exists)
    final_adjacency = {}
    for edge in adjacency_list:
        src = edge[0]
        if src not in final_adjacency:
            final_adjacency[src] = edge
            
    print("Writing SQL seed file...")
    sql_path = os.path.join("..", "db", "seeds", "02_ml_generated_seed.sql")
    
    with open(sql_path, "w") as f:
        f.write("-- Auto-generated by ml/cluster_tracks.py\n\n")
        
        f.write("-- Vibe Clusters\n")
        for i, name in enumerate(vibe_names):
            f.write(f"INSERT INTO Vibe_Clusters (cluster_id, vibe_name) VALUES ({i+1}, '{name}') ON CONFLICT DO NOTHING;\n")
            
        f.write("\n-- Cluster Adjacency\n")
        for src, dest, delta, dist in final_adjacency.values():
            f.write(f"INSERT INTO Cluster_Adjacency (cluster_id, adjacent_cluster_id, energy_delta) VALUES ({src}, {dest}, {delta}) ON CONFLICT DO NOTHING;\n")
            
        f.write("\n-- Tracks (Sample of 100 for brevity in seed, out of 1000 generated)\n")
        for i in range(100):
            mapped_cluster = cluster_mapping[cluster_labels[i]]
            duration = int(np.random.normal(210, 30))
            f.write(f"INSERT INTO Tracks (track_id, cluster_id, title, artist_name, duration) VALUES ({i+1}, {mapped_cluster}, 'Track {i+1}', 'Synth Artist {i%10}', {duration}) ON CONFLICT DO NOTHING;\n")
            
    print(f"Done! Seed file written to {sql_path}")

if __name__ == "__main__":
    generate_and_cluster()
